### ISSUE TITLE
/sendtime throws a timeout was reached error first

### ISSUE THREAD

**Issue by jdrichardstech** [sego90/slack-timezoner#5]
/sendtime throws a Timeout Was Reached error then shows the text message with accurate time.

![sendtimerror](https://user-images.githubusercontent.com/1908887/28776289-020bb812-75c4-11e7-92a6-d75443715a53.png)

**Comment by dsegovia90** [comment]
Will look into it!

**Comment by dsegovia90** [comment]
Ok so. This is the thing with the slack app. We always have to respond to it in 2000ms, even if we don't send back any content on the body. Since you are sending a completely new message with the slack npm module, you are not actually responding to the request. So, just by adding a res.end() should do the trick.
